//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllureTouch.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class alluretouchdbEntities : DbContext
    {
        public alluretouchdbEntities()
            : base("name=alluretouchdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<imageediting> imageeditings { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<blogpost> blogposts { get; set; }
        public virtual DbSet<tag> tags { get; set; }
    }
}
